ansible_user: "ubuntu"
home_dir: "/home/{{ ansible_user }}"
kubeconfig: "{{ home_dir }}/.kube/config"
k3s_docker_image: "ghcr.io/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}:latest"
