#!/usr/bin/env python
"""Post-generation hook: adjusts files based on cookiecutter choices."""

import os

USE_HX_BOOST = "{{cookiecutter.use_hx_boost}}"
USE_STORAGE = "{{cookiecutter.use_storage}}"

BASE_HTML = os.path.join("templates", "base.html")
DEFAULT_BASE_HTML = os.path.join("templates", "default_base.html")
HX_BASE_HTML = os.path.join("templates", "hx_base.html")

SETTINGS_PY = os.path.join("config", "settings.py")
URLS_PY = os.path.join("config", "urls.py")
PYPROJECT_TOML = "pyproject.toml"
ENV_EXAMPLE = ".env.example"
TERRAFORM_STORAGE = os.path.join("terraform", "hetzner", "storage.tf")

# ── hx-boost ──────────────────────────────────────────────────────────────────


def disable_hx_boost() -> None:
    """Remove hx-boost wiring when the user opts out."""
    # base.html: drop the HTMX/full-page switch, just extend default_base
    with open(BASE_HTML, "w") as f:
        f.write('{% extends "default_base.html" %}\n')

    # default_base.html: remove hx-boost attribute from <body>
    with open(DEFAULT_BASE_HTML) as f:
        content = f.read()
    content = content.replace('\n    hx-boost="true"', "")
    with open(DEFAULT_BASE_HTML, "w") as f:
        f.write(content)

    # hx_base.html is only needed for boosted navigation — remove it
    if os.path.exists(HX_BASE_HTML):
        os.remove(HX_BASE_HTML)


# ── storage ───────────────────────────────────────────────────────────────────

_SETTINGS_STORAGE_BLOCK = """
# Media files / Object Storage

MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / "media"

if env.bool("USE_S3_STORAGE", default=False):
    _base_storages = vars().get("STORAGES", {})
    STORAGES = {
        **_base_storages,
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }
    AWS_ACCESS_KEY_ID = env("HETZNER_STORAGE_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = env("HETZNER_STORAGE_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = env("HETZNER_STORAGE_BUCKET")
    AWS_S3_ENDPOINT_URL = env("HETZNER_STORAGE_ENDPOINT")
    AWS_S3_REGION_NAME = env("HETZNER_STORAGE_REGION", default="fsn1")
    AWS_DEFAULT_ACL = "public-read"
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
"""

_URLS_MEDIA_IMPORT = "from django.conf.urls.static import static\n"

_URLS_MEDIA_BLOCK = """
if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

_ENV_STORAGE_BLOCK = """
# Object Storage (Hetzner S3-compatible)
# Enable in production once the bucket is provisioned (see terraform/hetzner/storage.tf)
# USE_S3_STORAGE=true
# HETZNER_STORAGE_ACCESS_KEY=
# HETZNER_STORAGE_SECRET_KEY=
# HETZNER_STORAGE_BUCKET={{cookiecutter.project_slug}}-media
# HETZNER_STORAGE_ENDPOINT=https://fsn1.your-objectstorage.com
# HETZNER_STORAGE_REGION=fsn1
"""

_PYPROJECT_STORAGES_DEP = '    "django-storages[s3]>=1.14.4",\n'
# Insert after this anchor line in the dependencies array
_PYPROJECT_ANCHOR = '    "whitenoise[brotli]>=6.11.0",\n'


def setup_storage() -> None:
    """Wire up django-storages, media settings, and Hetzner terraform config."""

    # pyproject.toml: insert django-storages into dependencies
    with open(PYPROJECT_TOML) as f:
        content = f.read()
    if _PYPROJECT_ANCHOR in content:
        content = content.replace(
            _PYPROJECT_ANCHOR,
            _PYPROJECT_ANCHOR + _PYPROJECT_STORAGES_DEP,
        )
        with open(PYPROJECT_TOML, "w") as f:
            f.write(content)

    # config/settings.py: append media + S3 block
    with open(SETTINGS_PY, "a") as f:
        f.write(_SETTINGS_STORAGE_BLOCK)

    # config/urls.py: add static media serving import + urlpattern
    with open(URLS_PY) as f:
        urls_content = f.read()
    # Insert import after the existing static-related import line
    urls_content = urls_content.replace(
        "from django.conf import settings\n",
        "from django.conf import settings\n" + _URLS_MEDIA_IMPORT,
    )
    urls_content += _URLS_MEDIA_BLOCK
    with open(URLS_PY, "w") as f:
        f.write(urls_content)

    # .env.example: append storage vars
    with open(ENV_EXAMPLE, "a") as f:
        f.write(_ENV_STORAGE_BLOCK)

    # terraform/hetzner/storage.tf already generated by cookiecutter;
    # nothing to do — the file is included in the template tree.


def remove_storage_terraform() -> None:
    """Remove the storage terraform file when storage is not used."""
    if os.path.exists(TERRAFORM_STORAGE):
        os.remove(TERRAFORM_STORAGE)
    # Remove the terraform/hetzner dir if now empty
    tf_hetzner = os.path.join("terraform", "hetzner")
    if os.path.isdir(tf_hetzner) and not os.listdir(tf_hetzner):
        os.rmdir(tf_hetzner)
    tf_dir = "terraform"
    if os.path.isdir(tf_dir) and not os.listdir(tf_dir):
        os.rmdir(tf_dir)


# ── main ──────────────────────────────────────────────────────────────────────

if USE_HX_BOOST == "n":
    disable_hx_boost()

if USE_STORAGE == "y":
    setup_storage()
else:
    remove_storage_terraform()
